title: "Dr. Prasanta Majee"
name: "Dr. Prasanta Majee"
description: "Environmental Engineer | Soil & Groundwater Contamination | Adsorption & Remediation"
url: "https://prasantamajee.github.io"
baseurl: ""

# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Author

author:
  name: "Dr. Prasanta Majee"
  email: "prasantahit14@gmail.com"

# Social Links

github_username: prasantamajee
linkedin: https://www.linkedin.com/in/prasanta-majee
google_scholar: https://scholar.google.com/citations?user=vA-GyXcAAAAJ&hl=en&oi=ao

# Navigation
header_pages:
  - about.md
  - research.md
  - publications.md
  - projects.md
  - cv.md
  - contact.md
